"use strict";

export const LOAD_BEER_DIRECTORY_SUCCESS = "LOAD_BEER_DIRECTORY_SUCCESS";
export const FETCH_STYLE_CONTENTS_SUCCESS = "FETCH_STYLE_CONTENTS_SUCCESS";
export const FETCH_BEER_DATA_SUCCESS = "FETCH_BEER_DATA_SUCCESS";

export const FETCH_NEARBY_BREWERIES_SUCCESS = "FETCH_NEARBY_BREWERIES_SUCCESS";
export const FETCH_BEER_SEARCH_SUCCESS = "WE_FOUND_IT";

export const REQUEST_SENT = "REQUEST_SENT";
export const REQUEST_RECEIVED_SUCCESSFUL = "REQUEST_RECEIVED_SUCCESSFUL";
export const REQUEST_RECEIVED_ERROR = "REQUEST_RECEIVED_ERROR";

export const DO_YOU_BELONG_HERE = "YOU_BELONG_HERE?";
export const CHECK_ACTIVE_USER = "CHECK_ACTIVE_USER";
export const ACTIVE_USER_CONFIRMED = "ACTIVE_USER_CONFIRMED";
export const INACTIVE_USER_CONFIRMED = "INACTIVE_USER_CONFIRMED";
export const LOGOUT_USER = "BYE_BYE";

export const SHOW_AUTH0_LOCK = "SHOW_LOCK";
export const AUTH0_LOCK_SUCCESS = "AUTH0_LOCK_SUCCESS";
export const AUTH0_LOCK_ERROR = "AUTH0_LOCK_ERROR";

export const UPDATE_ACTIVE_USER = "UPDATE_ACTIVE_USER";
export const UPDATE_USER_LOCATION = "THERE_YOU_ARE";