"use strict";

export const LOAD_BEER_DIRECTORY_SUCCESS = "LOAD_BEER_DIRECTORY_SUCCESS";
export const FETCH_STYLE_CONTENTS_SUCCESS = "FETCH_STYLE_CONTENTS_SUCCESS";
export const FETCH_BEER_SUCCESS = "FETCH_BEER_SUCCESS";


export const SEND_OUT_REQUEST = "SEND_OUT_REQUEST";
export const REQUEST_SENT_ERROR = "REQUEST_SENT_ERROR";

